#!/bin/sh

AddPackages()
{
PKGDIR=/usr/share/siduction-scripts/packages

if [ -e /etc/default/distro ]; then
    . /etc/default/distro
fi

settings_version=$(echo $FLL_WALLPAPER | cut -d / -f 5)

if [ -n $(dpkg -l | grep Xorg) ]; then
    dest_platform=nox
    else
    dest_platform=xorg
fi

case $1 in
        cinnamon)
        PACK_PROFILE=cinnamon
        ;;
        gnome)
        PACK_PROFILE=gnome
        ;;
        kde)
        PACK_PROFILE=kde
        ;;
        plasma5)
        PACK_PROFILE=plasma5
        ;;
        lxde)
        PACK_PROFILE=lxde
        ;;
        lxqt)
        PACK_PROFILE=lxqt
        ;;
        lxqt-qt5)
        PACK_PROFILE=lxqt-qt5
        ;;
        mate)
        PACK_PROFILE=mate
        ;;
        rqt)
        PACK_PROFILE=rqt
        ;;
        siducation-full)
        PACK_PROFILE=siducation-full
        ;;
        siducation-lite)
        PACK_PROFILE=siducation-lite
        ;;
        xfce)
        PACK_PROFILE=xfce
        ;;
        custom)
        PACK_PROFILE=custom
        ;;
        *)
        ;;
esac

if [ "$PACK_PROFILE" = "custom" ]; then
    if [ ! -f ${PKGDIR}/custom ] ; then
        echo '######################################################'
        echo 'WARNING custom pkglist file not found!'
        echo 'Please add file /usr/share/siduction-scripts/custom.'
        echo 'Please use as template /usr/share/siduction-scripts/custom.ex file.'
        echo "WARNING don't add inexistent packages names to don't get in trouble."
        echo 'Thank you !'
        echo '######################################################'
        exit 1
    else
    # moves custom pkg list to custom-pklist.orig and show a message about it
    echo '######################################################'
    echo "Cpying custom pkglist  to custom.orig"
    echo "If you don't need it anymore you should remove it."
    echo '######################################################'
    awk '/^packages/,/^"""/' ${PKGDIR}/${PACK_PROFILE}  | grep -v '"""' | grep -v '#' > ${PKGDIR}/${PACK_PROFILE}-pkglist
    cp ${PKGDIR}/$PACK_PROFILE ${PKGDIR}/${PACK_PROFILE}.orig
    fi
else

case ${settings_version} in 
     whiteroom)
     echo "        siduction-settings-${PACK_PROFILE}-${settings_version}" > ${PKGDIR}/${PACK_PROFILE}-pkglist
     echo "        siduction-art-${PACK_PROFILE}-${settings_version}" >> ${PKGDIR}/${PACK_PROFILE}-pkglist
     ;;
     indiansummer)
     echo "        siduction-settings-${PACK_PROFILE}-${settings_version}" > ${PKGDIR}/${PACK_PROFILE}-pkglist
     echo "        siduction-art-${PACK_PROFILE}-${settings_version}" >> ${PKGDIR}/${PACK_PROFILE}-pkglist
     #echo "        siduction-art-wallpaper-${settings_version}" >> ${PKGDIR}/${PACK_PROFILE}-pkglist
     ;;
     *)
    echo "        siduction-settings-${PACK_PROFILE}-paintitblack" > ${PKGDIR}/${PACK_PROFILE}-pkglist
    echo "        siduction-art-${PACK_PROFILE}-paintitblack" >> ${PKGDIR}/${PACK_PROFILE}-pkglist
    echo "        siduction-art-wallpaper-paintitblack" >> ${PKGDIR}/${PACK_PROFILE}-pkglist
     ;;
esac




    # get using curl pyfll requested PACK_PROFILE or show a message for custom pkg list

        echo "Fetching siduction ${PACK_PROFILE}  profile list."
        sleep 2
        curl -'#' -o  ${PKGDIR}/${PACK_PROFILE} http://bugs.siduction.org/projects/pyfll/repository/revisions/master/raw/pyfll/packages/$PACK_PROFILE

    # Reads packages from packages profile
    awk '/^packages/,/^"""/' ${PKGDIR}/${PACK_PROFILE}  | grep -v '"""' | grep -v '#' >> ${PKGDIR}/${PACK_PROFILE}-pkglist

    # Search main file package for include dependecies
    # and build an depends file ( depends )
    awk '/^deps/,/^"""/' ${PKGDIR}/${PACK_PROFILE} | grep -v '"""' | grep -v '#' > ${PKGDIR}/${PACK_PROFILE}-deps

    # Search if we have NOX or XORG 
    
   case ${dest_platform} in
        xorg)
        cat ${PKGDIR}/${PACK_PROFILE}-deps | grep -v 200 | grep -v 100 | grep -v 300 |grep -v 500 >  ${PKGDIR}/${PACK_PROFILE}-depends
        ;;
        nox)
        cat ${PKGDIR}/${PACK_PROFILE}-deps | grep -v live | grep -v fll | grep -v installer >  ${PKGDIR}/${PACK_PROFILE}-depends
        echo "        siduction-settings-lightdm-gtk-${settings_version}" >> ${PKGDIR}/${PACK_PROFILE}-pkglist
        ;;
        *)
        echo "You can use addpkg only over on installed NOX or XORG siduction."
        ;;
    esac

    while read pkgdepends ; do
        echo "Fetching for ${PACK_PROFILE} profile $pkgdepends depend." 
        curl -'#' -o ${PKGDIR}/$pkgdepends-depfiles http://bugs.siduction.org/projects/pyfll/repository/revisions/master/raw/pyfll/packages/packages.d/$pkgdepends
    done < ${PKGDIR}/${PACK_PROFILE}-depends 

    for i in ${PKGDIR}/*-depfiles; do
     awk '/^packages/,/^"""/' ${i} | grep -v '"""' | grep -v '#' >> ${PKGDIR}/${PACK_PROFILE}-pkglist
    done

    # Removes temporary files
    if [ -f ${PKGDIR}/${PACK_PROFILE}-pkglist ] ; then
        rm -f ${PKGDIR}/*-dep*
        rm -f ${PKGDIR}/${PACK_PROFILE}
    fi

 
    fi


# install files
apt-get install $(cat ${PKGDIR}/${PACK_PROFILE}-pkglist)

# removes built package list 
rm -f /usr/share/siduction-scripts/packages/${PACK_PROFILE}-pkglist
}

case "$1" in
    cinnamon|custom|gnome|kde|plasma5|lxde|lxqt|lxqt-qt5|mate|rqt|siducation-full|siducation-lite|xfce)
    AddPackages $1
    ;;
    *)
        echo "Usage: addpkg {cinnamon|custom|gnome|kde|plasma5|lxde|lxqt|lxqt-qt5|mate|rqt|siducaion-full|siducation-lite|xfce}"
        exit 1
    ;;
esac



