#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	[ -x "$(which su-to-root)" ] && exec su-to-root -X -c "$0" "$@"
	printf "ERROR: $(basename ${0}) needs root capabilities, please start it as root.\n\n" >&2
	exit 1
fi

DPI=100
[ "${1}" ] && DPI="${1}"

if [ ${DPI} -eq ${DPI} ] && [ -w /etc/kde4/kdm/kdmrc ]; then

	sed -i	-e "s/\(^ServerArgsLocal\=.*\)\ \-dpi[ \t]*[0-9]*\(.*$\)/\1\2/" \
			-e "s/\(^ServerArgsLocal\=.*\)\-dpi[ \t]*[0-9]*\(.*$\)/\1\2/" \
			-e "s/\(^ServerArgsLocal\=.*\) *$/\1/" \
			-e "s/^ServerArgsLocal\=.*$/& \-dpi ${DPI}/" \
				/etc/kde4/kdm/kdmrc

	printf "KDM setting was changed to $DPI. You can use another value like:\n"
	printf "$(basename ${0}) 75\n"
	printf "Now restart kdm (/etc/init.d/kdm restart)\n\n"
else
	echo "ERROR: parameter ${DPI} not a number." >&2
	echo "Usage: $(basename ${0}) [dpi]" >&2
fi
