#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	[ -x "$(which su-to-root)" ] && exec su-to-root -X -c "$0" "$@"
	printf "ERROR: $0 needs root capabilities, please start it as root.\n\n" >&2
	exit 1
fi

sed -i "/^[ \t]*gateway/d" /etc/network/interfaces

/etc/init.d/networking restart

