#!/bin/bash
#
# just makes a siduction-wrapper
#
# uses wgetpaste from http://wgetpaste.zlin.dk/
# free to use, found in gentoo
#
export INFO_COMMAND="infobash "
export INFO_ARGS="-v 2 0"
export DEFAULT_NICK="siduction user"
export DEFAULT_SERVICE="codepad"

/usr/bin/wgetpaste "$@"



