#!/bin/sh
# preinst script for #PACKAGE#
set -e

case "$1" in
    install|upgrade)
        rm -rf /usr/share/sidu-installer

        rm -f /usr/share/sidu-base/scripts/checkupdate.py
        rm -f /usr/share/sidu-base/scripts/packetupdate.py

        rm -f /usr/share/sidu-base/backend/automount-control.sh
        rm -f /usr/share/sidu-base/backend/install.sh
        rm -f /usr/share/sidu-base/backend/partinfo.pl
        rm -f /usr/share/sidu-base/backend/partinfo.sh
        rm -f /usr/share/sidu-base/backend/timezoneinfo.sh
        rm -f /usr/share/sidu-base/backend/firmware.sh
        rm -f /usr/share/sidu-base/backend/firmware.pl
        rm -f /usr/share/sidu-base/backend/nonfree.sh
        rm -f /usr/share/sidu-base/backend/autopart.sh
        rm -f /usr/share/sidu-base/backend/autopart.pl

        rm -rf /var/cache/sidu-base/*
        [ -d /var/cache/sidu-base ] && mkdir -p /var/cache/sidu-base/public
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
